//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneLogs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class ColumnSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ColumnSettings defaultInstance = ((ColumnSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ColumnSettings())));
        
        public static ColumnSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SessionIDColumn {
            get {
                return ((int)(this["SessionIDColumn"]));
            }
            set {
                this["SessionIDColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int FromNameColumn {
            get {
                return ((int)(this["FromNameColumn"]));
            }
            set {
                this["FromNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int FromNumberColumn {
            get {
                return ((int)(this["FromNumberColumn"]));
            }
            set {
                this["FromNumberColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ToNameColumn {
            get {
                return ((int)(this["ToNameColumn"]));
            }
            set {
                this["ToNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ToNumberColumn {
            get {
                return ((int)(this["ToNumberColumn"]));
            }
            set {
                this["ToNumberColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int CallResultColumn {
            get {
                return ((int)(this["CallResultColumn"]));
            }
            set {
                this["CallResultColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int CallLengthColumn {
            get {
                return ((int)(this["CallLengthColumn"]));
            }
            set {
                this["CallLengthColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int HandleTimeColumn {
            get {
                return ((int)(this["HandleTimeColumn"]));
            }
            set {
                this["HandleTimeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int StartTimeColumn {
            get {
                return ((int)(this["StartTimeColumn"]));
            }
            set {
                this["StartTimeColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int CallDirectionColumn {
            get {
                return ((int)(this["CallDirectionColumn"]));
            }
            set {
                this["CallDirectionColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public int CallQueueColumn {
            get {
                return ((int)(this["CallQueueColumn"]));
            }
            set {
                this["CallQueueColumn"] = value;
            }
        }
    }
}
